### PR TITLE
Add scribe note for HMM's

### PR DESCRIPTION
**Pull request by nleroy917**
This is my scribing note for Hidden Markov Models. The only issue is running `make` gives me the following error:

```
WARNING: pandoc-crossref was compiled with pandoc 2.17.0.1 but is being run through 2.17.1.1. This is not supported. Strange things may (and likely will) happen silently.
```
The PDF looks ok, though. Thanks!

### CODE REVIEW

**Comment by nleroy917** [comment]
@aakrosh Not sure if you get notifications for PR's, but this is my scribing assignment. Thank you!

**Comment by aakrosh** [comment]
Thanks Nathan. I will integrate this and get back to you.

**Comment by aakrosh** [comment]
Nathan, I have integrated your markdown, but left out the scribe.pdf.

**Comment by nleroy917** [comment]
Thank you!

**Pull request closed without merging**
